artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_url: https://drive.google.com/file/d/154W-4p6zzoshbNrcSQjvMSltL52EFUE4/view?usp=sharing
  local_data_file: artifacts/data_ingestion/Dataset.zip
  unzip_dir: artifacts/data_ingestion

data_preparation:
  root_dir: artifacts/data_preparation
  data_dir: artifacts/data_ingestion/Intel_Image_Dataset
  train_dir: artifacts/data_preparation/train
  test_dir: artifacts/data_preparation/test
  val_dir: artifacts/data_preparation/val

prepare_model:
  root_dir: artifacts/prepare_model
  model_dir: artifacts/prepare_model/model.h5

training:
  root_dir: artifacts/training
  model_dir: artifacts/prepare_model/model.h5
  trained_model_dir: artifacts/training/model.h5
  history_dir: artifacts/training/history.json

model_evaluation:
  root_dir: artifacts/evaluation
  trained_model_dir: artifacts/training/model.h5
  history_dir: artifacts/training/history.json
  graph_dir: artifacts/evaluation/graphs.png
  val_dir: artifacts/data_preparation/val